CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);
INSERT INTO STUDENT(ROLLNO,NAME,MARKS,GRADE,CITY)
VALUES
(101,"ANIL",78,"C","PUNE"),
(102,"BHUMIKA",93,"A","MUMBAI"),
(103,"CHETAN",85,"B","MUMBAI"),
(104,"DHRUV",96,"A","DELHI"),
(105,"EMANUEL",12,"F","DELHI"),
(106,"FARAB",82,"B","DELHI");

-- SHOW ALL COLUMN OF TABLE
SELECT * FROM STUDENT;

-- SEE SPECIFIC COLUMN OF TABLE
SELECT ROLLNO,NAME,MARKS
FROM STUDENT;

-- I WANT UNIQUE values OF CITY 
SELECT DISTINCT CITY FROM STUDENT;

-- WHERE CLAUSE FIDN THOSE STUDENT NAME WHOSE MARKS IS GREATER THEN 90

SELECT * FROM STUDENT
WHERE MARKS>90;

-- FIND THOSE STUDENT NAME WHO BELONGS TO MUMBAI
SELECT NAME,CITY FROM STUDENT
WHERE CITY="MUMBAI";

-- FIND THOSE STUDENT WHOSE MARKS IS GREATER THAN 80 AND BELONGS TO MUMBAI
SELECT * FROM STUDENT
WHERE MARKS>80 AND CITY="MUMBAI";

-- FIND THOSE STUDENT WHICH MARKS IS BETWEEN 80 AND 90
SELECT ROLLNO,NAME FROM STUDENT
WHERE MARKS BETWEEN 80 AND 90;

-- FIND THOSE STUDENT THEY CAN BELONGS TO MUMBAI OR PUNE OR UP AND PUNJAB
SELECT * FROM STUDENT 
WHERE CITY IN("MUMBAI","LUCKNOW","PUNE");

-- I WANT ONLY 3 TUPLER OR ROWS FROM STUDENT
SELECT * FROM STUDENT 
LIMIT 3;


-- I WANT STUDENT TABLE BY ORDER OF CITY
SELECT * FROM STUDENT ORDER BY GRADE DESC;


-- COUNT(),MAX(),MIN(),SUM(),AVG()

-- FIND THOSE STUDENT WHO GET MAXIMUM MARKS

SELECT MAX(MARKS)
FROM STUDENT;


-- FIND THE CITY AND THEIR NO OF STUDENT
SELECT CITY,COUNT(ROLLNO)
FROM STUDENT
GROUP BY CITY;

-- FIND THE AVG MARKS OF EACH CITY
SELECT CITY,AVG(MARKS)
FROM STUDENT
GROUP BY CITY;

-- HAVING CLAUSE
-- COUNT NO OD STUDENT IN EACH CITY WHERE MAX MARKS CROSS 90
SELECT CITY,COUNT(ROLLNO)
FROM STUDENT
GROUP BY CITY
HAVING MAX(MARKS)>90;

-- UPDATE 
SET SQL_SAFE_UPDATES=0;

-- I WANT TO CHANGE ALL GRADE A TO O 
UPDATE STUDENT
SET GRADE="O"
WHERE GRADE="A";

SELECT * FROM STUDENT;

--  ROLL 105 STUDENT MARKS SHOULD BE 92
UPDATE STUDENT
SET MARKS=92
WHERE ROLLNO=105;

-- GIVE GRADE B WHOSE STUDENT MARKS IS BETWEEN 80 TO 90
UPDATE STUDENT
SET GRADE="B"
WHERE MARKS BETWEEN 80 AND 90;
SELECT * FROM STUDENT;

-- UPDATE ALL STUDENT MARKS BY 1
UPDATE STUDENT
SET   MARKS=MARKS+1;


-- DELETE QUERY
-- DELETE THOSE STUDENT WHOSE MARKS IS LESS THAN 33
DELETE FROM STUDENT
WHERE MARKS < 33;

-- table relater query
-- alter operation to change the schema

-- add column

ALTER TABLE STUDENT
ADD COLUMN AGE INT NOT NULL DEFAULT 19;

-- DROP COLUMN
ALTER TABLE STUDENT
DROP COLUMN AGE;

-- RENAME TABLE NAME
ALTER TABLE STU
RENAME TO STUDENT;



SELECT * FROM STUDENT;

-- IN THE TABLE STUDENT 
-- 1 CHANGE THE NAME OF COLUMN "NAME" TO "FULL_NAME"
ALTER TABLE STUDENT
CHANGE NAME  FULLNAME VARCHAR(50);

-- 2 DELETE ALL THE STUDENT WHO SCORED MARKS LESS THAN 80
DELETE FROM STUDENT
WHERE MARKS<80;

-- DELTE CULUMN GRADE
ALTER TABLE STUDENT
DROP COLUMN GRADE;
